### ISSUE TITLE
[Crash]: Create mision

### ISSUE THREAD

**Issue by mogcid** [Iskariot53/MinecoloniesCreateandConquer#3]
### Possible Fixes

Yes

### Modpack Version

b0.0.9

### What happened?

Crash server du a create mission 
[crash-2024-11-22_10.34.17-server.txt](https://github.com/user-attachments/files/17868104/crash-2024-11-22_10.34.17-server.txt)

### Crash Log

https://github.com/user-attachments/files/17868104/crash-2024-11-22_10.34.17-server.txt

**Comment by Iskariot53** [comment]
Log

**Comment by mogcid** [comment]
try to be nice in your next comment, anyway no need to continue your modpack, gratuitous meanness, moreover if you do not know how to read a crash report.

aused by: java.lang.RuntimeException: java.io.EOFException
	at com.kryeit.missions.DataStorage.<init>(DataStorage.java:35) ~[missions-forge-0.3.6.jar%23876!/:?] {re:mixin,re:classloading}
	at com.kryeit.missions.MissionManager.<clinit>(MissionManager.java:44) ~[missions-forge-0.3.6.jar%23876!/:?] {re:mixin,re:classloa
... 19 more
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:?] {}
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:?] {}
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:?] {}
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:?] {}
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:?] {}
	at net.minecraft.nbt.NbtIo.m_202493_(NbtIo.java:30) ~[server-1.20.1-20230612.114412-srg.jar%231021!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.nbt.NbtIo.m_128939_(NbtIo.java:34) ~[server-1.20.1-20230612.114412-srg.jar%231021!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.nbt.NbtIo.m_128937_(NbtIo.java:25) ~[server-1.20.1-20230612.114412-srg.jar%231021!/:?] {re:classloading,pl:accesstransformer:B}
	at com.kryeit.missions.DataStorage.<init>(DataStorage.java:32) ~[missions-forge-0.3.6.jar%23876!/:?] {re:mixin,re:classloading}
	at com.kryeit.missions.MissionManager.<clinit>(MissionManager.java:44) ~[missions-forge-0.3.6.jar%23876!/:?] {re:mixin,re:classloading}
	... 19 more
